#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';


use Components\Commands\GenerateController;
use Components\Commands\GenerateMiddleware;
use Components\Commands\GenerateMigration;
use Components\Commands\GenerateModel;
use Components\Commands\GenerateSeeder;
use Components\Commands\SeedRun;
use Symfony\Component\Console\Application;

$application = new Application('ZenTerminal', '1.0.0');


$application->add(new GenerateController());
$application->add(new GenerateMiddleware());
$application->add(new GenerateModel());
$application->add(new GenerateSeeder());
$application->add(new GenerateMigration());
$application->add(new SeedRun());
$application->add(new \Components\Commands\Migrate());
$application->add(new \Phinx\Console\Command\Status());

$application->run();
