<?php


namespace Framework\Commands\Phinx;

use Phinx\Console\Command\Create;

class GenerateMigration extends Create
{

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('phinx:create');
    }
}
