<?php


namespace Framework\Commands\Phinx;

use Phinx\Console\Command\SeedCreate;

class GenerateSeeder extends SeedCreate
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('phinx:seed:create');
    }
}
