<?php


namespace Components\Commands\Phinx;


class Migrate extends \Phinx\Console\Command\Migrate
{

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('phinx:migrate');
    }
}