<?php


namespace Components\Commands;


use Phinx\Console\Command\Create;

class GenerateMigration extends Create
{

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('make:migration');
    }

}