<?php


namespace Components\Commands;


use Phinx\Console\Command\SeedCreate;

class GenerateSeeder extends SeedCreate
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('make:seeder');
    }

}